In [1]:
import numpy as np
import pandas as pd

In [2]:
read_csv=pd.read_csv("50_Startups.csv")

In [3]:
read_csv.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [5]:
read=pd.get_dummies(read_csv,drop_first=True).astype(int)

In [6]:
read.head()

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349,136897,471784,192261,0,1
1,162597,151377,443898,191792,0,0
2,153441,101145,407934,191050,1,0
3,144372,118671,383199,182901,0,1
4,142107,91391,366168,166187,1,0

In [7]:
read.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [8]:
ind=read[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]
dep=read[['Profit']]

In [ ]:
# preprocess

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(ind,dep,test_size=0.3,random_state=42)

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [17]:
# model creation:
from sklearn.svm import SVR
reg=SVR(C= 1000,gamma= 'scale', kernel= 'rbf')
reg.fit(x_train,y_train)

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=1000)

In [18]:
# predict and evaluation:
from sklearn.metrics import r2_score
pred=reg.predict(x_test)

In [19]:
score=r2_score(y_test,pred)
score
if score<0.50:
    print(f"{score} -- Very worst model...")
else:
    print("good model")

0.06707185754086598 -- Very worst model...

In [21]:
# goes to deployement:
import pickle
file_name='single-pre_input_svr.sav'
create=pickle.dump(reg,open(file_name,'wb'))

In [22]:
# # check the file:
# preinput=sc.transform([[18000,5400,98451,0,1]])
# preinput

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([[-1.17759783, -4.6222801 , -1.10925925, -0.72231512,  1.47709789]])

In [23]:
# load=pickle.load(open('single-pre_input_svr.sav','rb'))
# re=load.predict(preinput)
# re

array([106558.05586511])