In [1]:
import pandas as pd

In [2]:
read_data=pd.read_csv("50_Startups.csv")

In [3]:
read_data.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
data_set=pd.get_dummies(read_data,drop_first=True).astype(int)

In [5]:
data_set.head()

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349,136897,471784,192261,0,1
1,162597,151377,443898,191792,0,0
2,153441,101145,407934,191050,1,0
3,144372,118671,383199,182901,0,1
4,142107,91391,366168,166187,1,0

In [6]:
data_set.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [13]:
# distribute feature and target:
inputs=data_set[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]
outputs=data_set['Profit']

In [14]:
# split:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(inputs,outputs,test_size=0.3,random_state=42)

In [15]:
# learning-random forest:
from sklearn.ensemble import RandomForestRegressor
rd=RandomForestRegressor(n_estimators=80,random_state=42)
rf=rd.fit(x_train,y_train)

In [16]:
# evaluation:
y_pred=rf.predict(x_test)

In [17]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)

In [18]:
r2

0.932168101510086

In [54]:
# save:
import pickle
file="finalize RF regression.sav"

In [55]:
create=pickle.dump(rf,open(file,'wb'))