In [25]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [26]:
file=pd.read_csv('50_Startups.csv')

In [27]:
file.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [28]:
file=pd.get_dummies(file,drop_first=True).astype(int)

In [29]:
file.head()

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349,136897,471784,192261,0,1
1,162597,151377,443898,191792,0,0
2,153441,101145,407934,191050,1,0
3,144372,118671,383199,182901,0,1
4,142107,91391,366168,166187,1,0

In [30]:
file.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [31]:
x=file[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]
y=file['Profit']

In [32]:
from sklearn.model_selection import KFold

In [49]:
kf=KFold(n_splits=3)

In [50]:
file.shape

(50, 6)

In [51]:
from sklearn.ensemble import RandomForestRegressor

In [52]:
from sklearn.metrics import r2_score

In [53]:
score=[]
for train_index,test_index in kf.split(x):
    x_train=x.iloc[train_index]
    x_test=x.iloc[test_index]
    y_train=y.iloc[train_index]
    y_test=y.iloc[test_index]
    model=RandomForestRegressor(n_estimators=80,random_state=42)
    model.fit(x_train,y_train)
    pred=model.predict(x_test)
    r2=r2_score(y_test,pred)
    score.append(r2)

In [54]:
np.mean(score)

np.float64(-2.4038900813606237)

In [55]:
score

[-2.5204541447611493, -2.8969241532342704, -1.7942919460864517]

In [57]:
# using grid searchcv:
from sklearn.model_selection import GridSearchCV